In [1]:
! pip install numpy
! pip install matplotlib
! pip install scikit-learn
! pip install pandas


[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier

In [3]:
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

In [14]:
iris = load_iris()

dataset = pd.DataFrame(iris.data, columns=iris.feature_names)

dataset['target'] = iris.target
dataset['species'] = dataset['target'].apply(lambda x: iris.target_names[x])

x = dataset.drop(['target', 'species'], axis=1)

y = dataset['species']

display(x)
display(y)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [15]:
xtrain, xvalidate, ytrain, yvalidate = train_test_split(x, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
xtrain_re = scaler.fit_transform(xtrain)
xvalidate_re = scaler.transform(xvalidate)

In [17]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(xtrain_re, ytrain)

pred = knn.predict(xvalidate_re)

[np.str_('versicolor') np.str_('setosa') np.str_('virginica')
 np.str_('versicolor') np.str_('versicolor') np.str_('setosa')
 np.str_('versicolor') np.str_('virginica') np.str_('versicolor')
 np.str_('versicolor') np.str_('virginica') np.str_('setosa')
 np.str_('setosa') np.str_('setosa') np.str_('setosa')
 np.str_('versicolor') np.str_('virginica') np.str_('versicolor')
 np.str_('versicolor') np.str_('virginica') np.str_('setosa')
 np.str_('virginica') np.str_('setosa') np.str_('virginica')
 np.str_('virginica') np.str_('virginica') np.str_('virginica')
 np.str_('virginica') np.str_('setosa') np.str_('setosa')] 73     versicolor
18         setosa
118     virginica
78     versicolor
76     versicolor
31         setosa
64     versicolor
141     virginica
68     versicolor
82     versicolor
110     virginica
12         setosa
36         setosa
9          setosa
19         setosa
56     versicolor
104     virginica
69     versicolor
55     versicolor
132     virginica
29         setosa
12

In [18]:
print(confusion_matrix(yvalidate, pred))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [19]:
print(classification_report(yvalidate, pred))
print(accuracy_score(yvalidate, pred))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

1.0
