<h1>Support Vector Machine</h1>
<p>The main objective of SVM is to find the optimal hyperplane in the n-dimensional plane that divides the datapoints in different classes in the feature space</p>
Detail about SVM here:
<a href="https://www.youtube.com/watch?v=efR1C6CvhmE">https://www.youtube.com/watch?v=efR1C6CvhmE</a>

In [1]:
! pip install numpy
! pip install scikit-learn
! pip install matplotlib
! pip install pandas


[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

In [43]:
iris = load_iris()

datasets = pd.DataFrame(iris.data, columns=iris.feature_names)
datasets['target'] = iris.target
datasets['species'] = datasets['target'].apply(lambda x: iris.target_names[x])

In [4]:
x = datasets.drop(['target', 'species'], axis=1)
y = datasets['species']

display(x, y)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [7]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

In [13]:

#make_pipeline : function is used to create a pipeline that sequentially applies a list of transformers and a final estimator
model = make_pipeline(StandardScaler(), SVC())

# #without using make_pipeline:
# scaler = StandardScaler()
# x_reshape = scaler.fit_transform(x)
# y_reshape = scaler.transform(y)

# svm = SVC()


xtrain, xvalidate, ytrain, yvalidate = train_test_split(x, y, test_size=0.2, random_state=42)
model.fit(xtrain, ytrain)

Pipeline(steps=[('standardscaler', StandardScaler()), ('svc', SVC())])

In [9]:
ypred = model.predict(xvalidate)
display(ypred)

array([np.str_('versicolor'), np.str_('setosa'), np.str_('virginica'),
       np.str_('versicolor'), np.str_('versicolor'), np.str_('setosa'),
       np.str_('versicolor'), np.str_('virginica'), np.str_('versicolor'),
       np.str_('versicolor'), np.str_('virginica'), np.str_('setosa'),
       np.str_('setosa'), np.str_('setosa'), np.str_('setosa'),
       np.str_('versicolor'), np.str_('virginica'), np.str_('versicolor'),
       np.str_('versicolor'), np.str_('virginica'), np.str_('setosa'),
       np.str_('virginica'), np.str_('setosa'), np.str_('virginica'),
       np.str_('virginica'), np.str_('virginica'), np.str_('virginica'),
       np.str_('virginica'), np.str_('setosa'), np.str_('setosa')],
      dtype=object)

In [11]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [12]:
print(confusion_matrix(yvalidate, ypred))
print(accuracy_score(yvalidate, ypred))
print(classification_report(yvalidate, ypred))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
1.0
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

